// Catálogo de inspección de vehículos (ingreso/retiro).
// Cada ítem se marca solo si presenta una novedad; por defecto se asume "Bien".

export interface ChecklistItem {
    categoria: string;
    item: string;
    estado: string;
    nota?: string;
}

// Estados posibles de una novedad al inspeccionar el vehículo.
export const ESTADOS_CHECK = [
    'Rasguño',
    'Rayado',
    'Abolladura',
    'Roto',
    'Fisurado / Trizado',
    'Quebrado',
    'Faltante',
    'Suelto / Flojo',
    'Manchado',
    'Sucio',
    'Desgastado',
    'Despintado',
    'Oxidado',
    'Fuga',
    'No funciona',
    'Otro',
] as const;

export const CHECKLIST_CATALOG: { categoria: string; icon: string; items: string[] }[] = [
    {
        categoria: 'Carrocería / Exterior',
        icon: 'solar:car-bold-duotone',
        items: [
            'Parachoques delantero',
            'Parachoques trasero',
            'Capó / Cofre',
            'Techo',
            'Puerta delantera izquierda',
            'Puerta delantera derecha',
            'Puerta trasera izquierda',
            'Puerta trasera derecha',
            'Guardafango delantero izquierdo',
            'Guardafango delantero derecho',
            'Guardafango trasero izquierdo',
            'Guardafango trasero derecho',
            'Maletera / Portón trasero',
            'Espejo lateral izquierdo',
            'Espejo lateral derecho',
            'Manijas de puertas',
            'Antena',
            'Emblemas / Insignias',
            'Placa delantera',
            'Placa trasera',
            'Molduras / Fajas laterales',
            'Estribos / Pisaderas',
        ],
    },
    {
        categoria: 'Lunas / Cristales',
        icon: 'solar:glass-water-bold-duotone',
        items: [
            'Parabrisas delantero',
            'Luna posterior',
            'Ventana delantera izquierda',
            'Ventana delantera derecha',
            'Ventana trasera izquierda',
            'Ventana trasera derecha',
            'Espejo retrovisor interior',
            'Láminas / Vidrio polarizado',
        ],
    },
    {
        categoria: 'Luces',
        icon: 'solar:lightbulb-bold-duotone',
        items: [
            'Faro delantero izquierdo',
            'Faro delantero derecho',
            'Luz trasera izquierda',
            'Luz trasera derecha',
            'Luz de freno (stop)',
            'Direccionales',
            'Neblineros',
            'Luz de placa',
            'Luz de retroceso',
            'Luces interiores',
        ],
    },
    {
        categoria: 'Llantas / Ruedas',
        icon: 'solar:wheel-bold-duotone',
        items: [
            'Llanta delantera izquierda',
            'Llanta delantera derecha',
            'Llanta trasera izquierda',
            'Llanta trasera derecha',
            'Llanta de repuesto',
            'Aros / Rines',
            'Tapas de aro / Copas',
            'Estado de cocada / labrado',
            'Pernos / Tuercas',
        ],
    },
    {
        categoria: 'Interior',
        icon: 'solar:armchair-bold-duotone',
        items: [
            'Tablero / Instrumentos',
            'Volante',
            'Asientos delanteros',
            'Asientos traseros',
            'Tapiz / Fundas',
            'Alfombras / Piso',
            'Radio / Multimedia',
            'Parlantes',
            'Aire acondicionado',
            'Calefacción',
            'Palanca de cambios',
            'Freno de mano',
            'Cinturones de seguridad',
            'Techo interior / Cielo raso',
            'Guantera',
            'Parasoles',
            'Encendedor / Tomacorriente USB',
            'Vidrios eléctricos',
            'Seguros / Cierre centralizado',
        ],
    },
    {
        categoria: 'Mecánica / Motor',
        icon: 'solar:settings-bold-duotone',
        items: [
            'Nivel de aceite',
            'Nivel de refrigerante',
            'Nivel de líquido de frenos',
            'Batería',
            'Sistema de frenos',
            'Fugas visibles (aceite / agua)',
            'Ruidos anormales',
            'Encendido del motor',
            'Testigos del tablero',
            'Limpiaparabrisas / Plumillas',
            'Claxon / Bocina',
            'Fajas / Correas',
            'Escape / Silenciador',
        ],
    },
    {
        categoria: 'Accesorios / Documentos entregados',
        icon: 'solar:clipboard-list-bold-duotone',
        items: [
            'Llaves (juego completo)',
            'Tarjeta de propiedad',
            'SOAT vigente',
            'Revisión técnica',
            'Manual del propietario',
            'Gata',
            'Llave de ruedas',
            'Triángulos de seguridad',
            'Extintor',
            'Botiquín',
            'Conos',
            'Chaleco reflectivo',
            'Herramientas',
            'Alarma / Control existente',
            'Autoradio / Consola',
            'Cargador / Cables',
        ],
    },
    {
        categoria: 'Estado general',
        icon: 'solar:magnifer-bold-duotone',
        items: [
            'Rayones generales',
            'Abolladuras generales',
            'Óxido / Corrosión',
            'Diferencias de pintura / Repintado',
            'Limpieza exterior',
            'Limpieza interior',
            'Olores (humedad / tabaco)',
            'Filtraciones de agua',
        ],
    },
];

export const keyOf = (categoria: string, item: string) => `${categoria}::${item}`;
